### ISSUE TITLE
$shipping_price i order.html returnerer Fragt = 0,00

### ISSUE THREAD

**Issue by mikkeltschentscher** [Shoporama/Massachusetts_v2#20]
`<{$shipping_price|number_format:2:",":"."}> `
Erstattes med
`<{$order->getShippingPrice()|number_format:2:",":"."}>`
Jævnfør; http://doc.shoporama.dk/Templates/orders#getShippingPrice.28.29_2

**Comment by lsolesen** [comment]
Kunne du måske lave et pull request på ændringen?

**Comment by mikkeltschentscher** [comment]
Næste gang, gerne.
