### ISSUE TITLE
Bygge caching ind i templatet

### ISSUE THREAD

**Issue by lsolesen** [Shoporama/Massachusetts_v2#32]
@KimDolleris Vil det være i orden at bytte noget blok caching direkte ind i templatet. For mig har det ikke været den bedste ud-af-boksen oplevelse at starte en butik med mange produkter på temaet, men tænker at blok-caching vil hjælpe på det.

**Comment by lsolesen** [comment]
@KimDolleris Fx noget i den her stil, men hvor cachen kunne laves flere steder https://github.com/Shoporama/Massachusetts_v2/pull/33

**Comment by KimDolleris** [comment]
Du fyrer den bare af @lsolesen. Optimer endelig hvor du tænker det giver mening. Jeg kommer ikke omkring dette så tit :)

**Comment by lsolesen** [comment]
Dette er implementeret her: https://github.com/Shoporama/Massachusetts_v2/commit/4283a7286dae3c80c7e5903eeb16d0ef9d11d1dd
